kind: Deployment
apiVersion: apps/v1
metadata:
  name: test01
spec:
  template:
    metadata:
      labels:
        app: test01
    spec:
      containers:
      - name: test01
        image: 363412468025.dkr.ecr.us-east-2.amazonaws.com/test01:latest
  selector:
    matchLabels:
      app: test01
---
kind: Service
apiVersion: v1
metadata:
  name: test01
spec:
  type: LoadBalancer
  selector:
    app: test01
  ports:
  - name: http
    port: 5001
    targetPort: 3001
